% Separate the SPECTRAIons_act.dat generated by GENE/IDL into time-specific files
function separate_fluxspectradata(sim,data_n,time_n)

    oldpath = path;
    path('../com', oldpath);
    f_path = 'path.txt';
    
    switch sim
        case {'GENE', 'gene'}
            FVER = 5;
            oldpath = addpath('../sim_data/GENE', '../sim_data/task_eq', '../sim_data/GENE/plot');
            dataC = GENEClass(f_path, data_n);
        otherwise
            error('Unexpected simulation type.');
    end

    % Specify the name of the text file
    file = sprintf('%sFLUXSPECTRAIons_act.dat', dataC.indir);
    
    % Read the text file
    fid = fopen(file, 'r'); % Open the file in read mode

    % Delete the first 5 lines
    for i = 1:5
        fgetl(fid);
    end
    
    for k = 1:2 % k=1:(ky), k=2:(kx)
        for l = 1:time_n
            % Repeat the process for tol_n times
            if feof(fid)
                break;
            end
            
            % Skip empty lines
            line = fgetl(fid);
            while isempty(line) && ~feof(fid)
                line = fgetl(fid);
            end
            
            % Process the line to extract time
            if contains(line, 'time =')
                % Extract time value using regular expression
                time_match = regexp(line, 'time = ([\w\.\-\s\pi]+)', 'tokens');
            
                time = str2double(strtrim(time_match{1}{1}));
                time = floor(time*10)/10;
                
                % Create or open the output file in append mode
                if k == 1
                    outfile = sprintf('%sSPECTRAIons_act_ky_%s.dat',dataC.indir,sprintf('%.0f',time));
                elseif k == 2
                    outfile = sprintf('%sSPECTRAIons_act_kx_%s.dat',dataC.indir,sprintf('%.0f',time));
                end
                fout = fopen(outfile, 'w'); % Open the file in write mode
                
                % Write the line with time to the output file
                fprintf(fout, '%s\n', line);
                
                % Delete the next two lines
                fgetl(fid);
                fgetl(fid);
                
                % Initialize lists for ky and n
                ky = zeros(64,1);
                n = zeros(64,1);
                
                % Read and store the following nky0 lines of numeric data
                for i = 1:64
                    if feof(fid)
                        break;
                    end
                    line = fgetl(fid);
                    data = sscanf(line, '%f %f');
                    ky(i) = data(1);
                    n(i) = data(2);
                    
                    % Write the line to the output file
                    fout = fopen(outfile, 'a'); % Open the file in append mode
                    fprintf(fout, '%s\n', line);
                end
                
                % Close the current output file
                fclose(fout);
            end
        end
    end
    % Close the input file
    fclose(fid);

    % Restore the path
    path(oldpath);
end
